name: Build Image2ASCII

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_FILE_PATH: Image2ASCII.vcxproj
  BUILD_CONFIGURATION: Release
  PLATFORM: x64
  OPENCV_DIR: C:\opencv

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download OpenCV
      shell: powershell
      run: |
        Invoke-WebRequest `
          -Uri "https://github.com/opencv/opencv/releases/download/5.0.0/opencv-5.0.0-windows.exe" `
          -OutFile "$env:RUNNER_TEMP\opencv.exe"

    - name: Install OpenCV
      shell: powershell
      run: |
        Start-Process `
          -FilePath "$env:RUNNER_TEMP\opencv.exe" `
          -ArgumentList "-y", "-oC:\" `
          -Wait

    - name: Build
      shell: powershell
      run: |
        msbuild "${{ env.PROJECT_FILE_PATH }}" `
          /m `
          /p:Configuration="${{ env.BUILD_CONFIGURATION }}" `
          /p:Platform="${{ env.PLATFORM }}" `
          /p:OPENCV_DIR="${{ env.OPENCV_DIR }}"
